apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: my-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-api
    spec:
      containers:
      - name: my-api
        image: my-api-image:latest  # Change to your actual API image
        ports:
          - name: http
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-api
  namespace: argo-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: my-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: argo-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: my-api
            port:
              number: 5000
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-demo
