apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
      - name: api
        imagePullPolicy: Never   # Use local image
        image: api-image:latest  # Ensure image is available locally
        ports:
          - name: http
            containerPort: 4021
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: argo-demo
spec:
  type: LoadBalancer  # Exposes API externally
  selector:
    app.kubernetes.io/name: api
  ports:
    - protocol: TCP
      port: 4021
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: argo-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: myapp.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 4021
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-demo
